// testing custom function definitions
var cool = lol
function loop
	HelloWorld
	HelloWorld
	HelloWorld
	HelloWorld
	HelloWorld
	HelloWorld
end

loop
PrintVars

//function test
//loop
//PrintVars
//end

test
test
test
test
test
test
test
test

// how i want methods with parameters to be ran:
//	name <= PARAMS_HERE
// of course replacing PARAMS_HERE with the required parameters and name with the name of the method

// what it thinks the test method is:
//	function test
//	function test

// WARNING: indentation may or may not work!